export * from "./Header";
export * from "./Footer";
export * from "./Title";
export * from "./Blog";
export * from "./Faq";
export * from "./OurDoctors"
export * from "./OurServices"
export * from "./AboutUs"
export * from "./PatientsSay"
